package com.example.kkgas.navigation

const val ROUT_HOME="home"
const val ROUT_ABOUT="about"
const val ROUT_SPLASH="splash"
const val ROUT_SIGNUP="signup"
const val ROUT_LOGIN="login"
const val ROUT_DASHBOARD="dashboard"
const val ROUT_DETAILS="details"
const val ROUT_ADDGAS="addgas"
const val ROUT_VIEWGAS="viewgas"
const val ROUT_MOREINFO="moreinfo"
const val ROUT_VIEWGASBUYER="viewgasbuyer"
const val ROUT_BOOKGAS="bookgas"
const val ROUT_VIEWBOOKEDGAS="viewbookedgas"